name: Update countdown

on:
  schedule:
    - cron: "17 0 * * *"
      timezone: "Europe/Moscow"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update countdown
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          MESSAGE_ID: ${{ secrets.MESSAGE_ID }}
        run: python bot.py
